### PR TITLE
workflows: Introduce static code check

### PR DESCRIPTION
**Pull request by martinpitt**
This runs on PRs, for some minimal validation. Start with pyflakes, this
can be extended to pycodestyle, YAML linting, etc. if/when desired.

----

Current main has quite a lot of errors:
```
./fedora_bot.py:100:9 local variable 'err' is assigned to but never used
./fedora_bot.py:101:29 undefined name 'e'
./fedora_bot.py:124:15 undefined name 'req'
./fedora_bot.py:129:9 local variable 'err' is assigned to but never used
./fedora_bot.py:130:29 undefined name 'e'
./fedora_bot.py:152:9 local variable 'err' is assigned to but never used
./fedora_bot.py:153:29 undefined name 'e'
```

Running the first version without any fixes, to confirm it fails as expected.

### CODE REVIEW

**Comment by martinpitt** [comment]
Ah heh, I suppose I'm a first-time contributor, so @ochosi probably needs to hit that "Approve workflow run" button or so?

**Comment by martinpitt** [comment]
I temporarily added a `push` trigger to the workflow, so that I can see it [on my fork](https://github.com/martinpitt/fedora-bot/actions). It [fails as expected](https://github.com/martinpitt/fedora-bot/runs/6482225422?check_suite_focus=true).

**Comment by martinpitt** [comment]
I added fixes for the errors, and the [workflow succeeds now](https://github.com/martinpitt/fedora-bot/runs/6482275864?check_suite_focus=true).

Re-pushing without the `push` trigger, as that's usually redundant.

**Comment by ochosi** [comment]
Oh my, the copy-paste errors :see_no_evil:

**Pull request merged**
